### ISSUE TITLE
Discard warning messages

### ISSUE THREAD

**Issue by dawidd6** [sharkdp/diskus#29]
Hi,

First let me illustrate the problem:

![Screenshot from 2019-05-22 14-53-35](https://user-images.githubusercontent.com/9713907/58175932-8685b800-7ca1-11e9-9309-1e743b4d414a.png)

Can we just discard those `could not read contents of directory` warnings?
They seem to be useless, cause running `diskus` as root produces the same output.

**Comment by Arcterus** [comment]
If the directories that can't be read are large enough, the results should be different.  Are those directories empty?

**Comment by dawidd6** [comment]
Yes, they are.

**Comment by Arcterus** [comment]
That explains why the results are the same then.

Basically, `diskus` can retrieve the metadata for a directory that can’t be read but can’t see the contents.  Because the directories are empty, the size given in the metadata is the actual size of the directory, so everything works out.

However, if the directory contained other files, the reported size should include the size of the directory itself (which might be stuff like the number of entries and the permissions of the directory or whatever the OS decides to report) as well as the sizes of the files contained within (recursively).  If `diskus` can’t read the contents of the directory, it can’t determine the sizes of the files contained within, so it just reports the size of the directory itself.  This would lead to a different final size, so `diskus` displays warnings to indicate that the final reported size may not be completely accurate.

**Comment by sharkdp** [comment]
It's just like @Arcterus said, yes.

We could potentially make this a bit more user-friendly, though. Maybe we could collect all access-errors while traversing the directory and then just print a single warning at the end that the result might be inaccurate since there were directories/files that could not be accessed.

**Comment by Arcterus** [comment]
I think it would be better to put the current behavior behind a `--verbose` flag and default to just mentioning the size may be inaccurate.

**Comment by sharkdp** [comment]
> put the current behavior behind a `--verbose` flag

Yes, sounds good.

> default to just mentioning the size may be inaccurate.

That's what I wanted to suggest, exactly. But I would only show the "may be inaccurate" warning if there were any I/O errors while traversing the directory.

**Comment by Arcterus** [comment]
Ah, that was what I meant.  I should have been clearer.
